# Compiler Configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djdk.tls.client.protocols=TLSv1.2
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# Module Project Configuration
project.android.compileSdk=37
project.android.minSdk=26
project.android.targetSdk=37
project.module-app.packageName=io.github.sky.apperrors
project.module-app.versionName="1.11"
project.module-app.versionCode=66
project.module-app.signing.keyAlias=public
project.module-app.signing.keyPassword="123456"
project.module-app.signing.storePassword="123456"
project.module-app.signing.storeFilePath=.secret/universal.p12
android.aapt2FromMavenOverride=/workspace/tools/android-sdk/build-tools/37.0.0/aapt2
